version: '3'

services:
  app:
    container_name: app
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    # command: ["npm", "start"]
    # image: testing-app //seria lo mismo con esto
    ports:
      - 3000:80 #puerto 3000 de mi localhost con el puerto 80 de la imagen Nginx que expuse